disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Freudian Couch"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "icons/logo.png"

[params.author]
name = "The Freudian Couch"
links = [
  { facebook = "https://www.facebook.com/profile.php?id=61580810498423" },
  { x-twitter = "https://x.com/CouchFreudian" },
  { instagram = "https://www.instagram.com/thefreudiancouch/"},
  { bluesky = "https://bsky.app/profile/thefreudiancouch.bsky.social"}
]
email = "thefreudiancouch@gmail.com"
