disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Freudian Couch"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "icons/logo.png"

[params.author]
name = "Adarsh Vijayaraghavan"
links = [
  { linkedin = "https://www.linkedin.com/in/adarsh-vijayaraghavan-25836219/" },
  { goodreads = "https://www.goodreads.com/user/show/4391307-adarsh" }
]
email = "adarshvijayaraghavan@gmail.com"
